
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__MprisPlayer_hpp__PROXY_MARSHAL_H
#define __dbusxx__MprisPlayer_hpp__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace org {
namespace freedesktop {

class MediaPlayer_proxy
: public ::DBus::InterfaceProxy
{
public:

    MediaPlayer_proxy()
    : ::DBus::InterfaceProxy("org.freedesktop.MediaPlayer")
    {
	     connect_signal(MediaPlayer_proxy, TrackChange, _TrackChange_stub);
	     connect_signal(MediaPlayer_proxy, StatusChange, _StatusChange_stub);
	     connect_signal(MediaPlayer_proxy, CapsChange, _CapsChange_stub);
	     connect_signal(MediaPlayer_proxy, TrackListChange, _TrackListChange_stub);
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    // Root Methods

    std::string Identity()
    {
        ::DBus::CallMessage call;
        call.member("Identity");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        std::string argout;
        ri >> argout;
        return argout;
    }

    void Quit()
    {
        ::DBus::CallMessage call;
        call.member("Quit");
        ::DBus::Message ret = invoke_method (call);
    }

    ::DBus::Struct< uint16_t, uint16_t > MprisVersion()
    {
        ::DBus::CallMessage call;
        call.member("MprisVersion");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        ::DBus::Struct< uint16_t, uint16_t > argout;
        ri >> argout;
        return argout;
    }
    //TrackList Methods

    std::map< std::string, ::DBus::Variant > GetMetadata(const int32_t& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("GetMetadata");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        std::map< std::string, ::DBus::Variant > argout;
        ri >> argout;
        return argout;
    }

    int32_t GetCurrentTrack()
    {
        ::DBus::CallMessage call;
        call.member("GetCurrentTrack");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t GetLength()
    {
        ::DBus::CallMessage call;
        call.member("GetLength");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t AddTrack(const std::string& argin0, const bool& argin1)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        wi << argin1;
        call.member("AddTrack");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    void DelTrack(const int32_t& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("DelTrack");
        ::DBus::Message ret = invoke_method (call);
    }

    void SetLoop(const bool& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("SetLoop");
        ::DBus::Message ret = invoke_method (call);
    }

    void SetRandom(const bool& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("SetRandom");
        ::DBus::Message ret = invoke_method (call);
    }

    void PlayTrack(const int32_t& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("PlayTrack");
        ::DBus::Message ret = invoke_method (call);
    }
    
    //Player Methods
    void Pause()
    {
        ::DBus::CallMessage call;
        call.member("Pause");
        ::DBus::Message ret = invoke_method (call);
    }

    void Stop()
    {
        ::DBus::CallMessage call;
        call.member("Stop");
        ::DBus::Message ret = invoke_method (call);
    }

    void Play()
    {
        ::DBus::CallMessage call;
        call.member("Play");
        ::DBus::Message ret = invoke_method (call);
    }

    void Prev()
    {
        ::DBus::CallMessage call;
        call.member("Prev");
        ::DBus::Message ret = invoke_method (call);
    }

    void Next()
    {
        ::DBus::CallMessage call;
        call.member("Next");
        ::DBus::Message ret = invoke_method (call);
    }

    void Repeat(const bool& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("Repeat");
        ::DBus::Message ret = invoke_method (call);
    }

    ::DBus::Struct< int32_t, int32_t, int32_t, int32_t > GetStatus()
    {
        ::DBus::CallMessage call;
        call.member("GetStatus");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        ::DBus::Struct< int32_t, int32_t, int32_t, int32_t > argout;
        ri >> argout;
        return argout;
    }

    void VolumeSet(const int32_t& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("VolumeSet");
        ::DBus::Message ret = invoke_method (call);
    }

    int32_t VolumeGet()
    {
        ::DBus::CallMessage call;
        call.member("VolumeGet");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    void PositionSet(const int32_t& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("PositionSet");
        ::DBus::Message ret = invoke_method (call);
    }

    int32_t PositionGet()
    {
        ::DBus::CallMessage call;
        call.member("PositionGet");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    std::map< std::string, ::DBus::Variant > GetMetadata()
    {
        ::DBus::CallMessage call;
        call.member("GetMetadata");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        std::map< std::string, ::DBus::Variant > argout;
        ri >> argout;
        return argout;
    }

    int32_t GetCaps()
    {
        ::DBus::CallMessage call;
        call.member("GetCaps");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    void VolumeUp(const int32_t& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("VolumeUp");
        ::DBus::Message ret = invoke_method (call);
    }

    void VolumeDown(const int32_t& argin0)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << argin0;
        call.member("VolumeDown");
        ::DBus::Message ret = invoke_method (call);
    }

    void Mute()
    {
        ::DBus::CallMessage call;
        call.member("Mute");
        ::DBus::Message ret = invoke_method (call);
    }

    void ShowOSD()
    {
        ::DBus::CallMessage call;
        call.member("ShowOSD");
        ::DBus::Message ret = invoke_method (call);
    }


public:

    /* signal handlers for this interface
    */
    virtual void TrackChange(const std::map< std::string, ::DBus::Variant >& argin0) = 0;
    virtual void StatusChange(const ::DBus::Struct< int32_t, int32_t, int32_t, int32_t >& argin0) = 0;
    virtual void CapsChange(const int32_t& argin0) = 0;
    virtual void TrackListChange(const int32_t& argin0) = 0;
private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
    */

    void _TrackChange_stub(const ::DBus::SignalMessage &sig)
    {
        ::DBus::MessageIter ri = sig.reader();

        std::map< std::string, ::DBus::Variant > arg0;
        ri >> arg0;
        TrackChange(arg0);
    }
    void _StatusChange_stub(const ::DBus::SignalMessage &sig)
    {
        ::DBus::MessageIter ri = sig.reader();

        ::DBus::Struct< int32_t, int32_t, int32_t, int32_t > arg0;
        ri >> arg0;
        StatusChange(arg0);
    }
    void _CapsChange_stub(const ::DBus::SignalMessage &sig)
    {
        ::DBus::MessageIter ri = sig.reader();

        int32_t arg0;
        ri >> arg0;
        CapsChange(arg0);
    }
    void _TrackListChange_stub(const ::DBus::SignalMessage &sig)
    {
        ::DBus::MessageIter ri = sig.reader();

        int32_t arg0;
        ri >> arg0;
        TrackListChange(arg0);
    }
};

} } 
namespace org {
namespace freedesktop {
namespace DBus {

class Peer_proxy
: public ::DBus::InterfaceProxy
{
public:

    Peer_proxy()
    : ::DBus::InterfaceProxy("org.freedesktop.DBus.Peer")
    {
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    void Ping()
    {
        ::DBus::CallMessage call;
        call.member("Ping");
        ::DBus::Message ret = invoke_method (call);
    }

    std::string GetMachineId()
    {
        ::DBus::CallMessage call;
        call.member("GetMachineId");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        std::string argout;
        ri >> argout;
        return argout;
    }


public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} } } 
#endif //__dbusxx__MprisPlayer_hpp__PROXY_MARSHAL_H
